### ISSUE TITLE
Can't save model with ManyToMany Field

### ISSUE THREAD

**Issue by artursmet** [torchbox/django-modelcluster#3]
I've found a bug in save of m2m related objects.
Steps to reproduce:
- Install wagtail CMS
- Create single Page model
- Create standard Django model
- Add `ManyToManyField` from your Page model to standard django model
- Try to create page instance

When you try to save it, you'll receive following error:

``` python
Traceback:
File "/home/artur/Projekty/demo/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  114.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/artur/Projekty/demo/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/home/artur/Projekty/demo/src/wagtail/wagtail/wagtailadmin/views/pages.py" in create
  172.             page = form.save(commit=False)  # don't save yet, as we need treebeard to assign tree params
File "/home/artur/Projekty/demo/local/lib/python2.7/site-packages/modelcluster/forms.py" in save
  257.             self.save_m2m()
File "/home/artur/Projekty/demo/local/lib/python2.7/site-packages/django/forms/models.py" in save_m2m
  96.                 f.save_form_data(instance, cleaned_data[f.name])
File "/home/artur/Projekty/demo/local/lib/python2.7/site-packages/django/db/models/fields/related.py" in save_form_data
  1527.         setattr(instance, self.attname, data)
File "/home/artur/Projekty/demo/local/lib/python2.7/site-packages/django/db/models/fields/related.py" in __set__
  835.         manager = self.__get__(instance)
File "/home/artur/Projekty/demo/local/lib/python2.7/site-packages/django/db/models/fields/related.py" in __get__
  825.             through=self.field.rel.through,
File "/home/artur/Projekty/demo/local/lib/python2.7/site-packages/django/db/models/fields/related.py" in __init__
  522.                                  (instance, source_field_name))
```

It tries to execute `save_m2m()` before saving page instance. Is there workaround for this issue?

**Comment by caioariede** [comment]
Hi guys,

I'm having a hard time trying to understand this line:
https://github.com/torchbox/django-modelcluster/blob/master/modelcluster/forms.py#L265

* Why the call to `save_m2m` only happens when `commit=False`?
* Why not call `save_m2m` only when `commit=True`?

The last one seems to solve the problem with many-to-many relationships, but I'm not aware of the side effects of this change.

**Comment by gasman** [comment]
@caioariede When `commit=True`, Django's own `save` method deals with saving m2m relations, so we don't have to do it in our own code. In fact, `save_m2m` is not even defined in that situation: https://github.com/django/django/blob/master/django/forms/models.py#L449-L456

**Comment by caioariede** [comment]
So what's the purpose of calling it manually? I read the comment but didn't get it.

**Comment by gasman** [comment]
The overall principle of django-modelcluster is that you can assign relations between objects (e.g. `band.members = [john, paul, george, ringo]`) and have it store those in memory, so that you can query those relations without them existing in the database. Django on its own does not support this - if you assign a relation like that, it will immediately try to write those objects to the database.

When you call `form.save(commit=False)`, you are telling Django "copy the form data to the model, without saving it to the database". This creates a problem if the form data contains M2M relations, because Django can *only* represent those relations by saving them to the database. To work around this, Django just copies the plain (non-relation) fields to the model, and generates a `save_m2m` method that you can call later, when you're ready to write your data back to the database.

With django-modelcluster, we don't need this workaround - we can write the relation data back to the model immediately on `form.save(commit=False)`, because the relations will be stored in memory, not written back to the database. So, in this piece of code, django-modelcluster is effectively saying "Take the actions that Django has postponed to the `save_m2m` method, and perform them now, because we know that we can safely do them without writing to the database".

**Comment by alexgleason** [comment]
I wrote a quick guide and explanation on how to implement M2M's using what's currently available. https://gist.github.com/alexgleason/09b1802b004babd74e96

**Comment by arlyon** [comment]
I'm currently having a similar issue. Adding a manytomany to an existing element in the db works fine, but when trying to create a new one with wagtail [Line 230] (https://github.com/torchbox/django-modelcluster/blob/master/modelcluster/forms.py#L230) in forms.py causes the error "[Model] needs to have a value for field [M2MField] before this many-to-many relationship can be used." However if I comment out the line, create an element, and then uncomment it, I can add [M2MField] to [Model] just fine.

**Comment by gasman** [comment]
Finally completed in #62!
