### ISSUE TITLE
Drop support for django 1.6?

### ISSUE THREAD

**Issue by theju** [torchbox/django-modelcluster#32]
Please update tox.ini to remove support for django 1.6 now that it is unsupported. You may also consider removing Python 2.6 which isn't available on any Linux based distribution. RHEL 7, which is the slowest in terms of updates, also comes with Python 2.7.

**Comment by gasman** [comment]
Hi @theju - thanks for the PR. I'm happy to drop Django 1.6 / Python 2.6 support in the next major release of django-modelcluster (which I'll possibly number as 1.0, to make the backwards-incompatibility explicit), so I've now merged this. I've also created a stable/0.6.x branch so that we still have the possibility of producing bugfix releases with Django 1.6 support (this is necessary because we'll continue to support Wagtail 0.8.x as a long-term-support release).

**Comment by theju** [comment]
Thanks @gasman. I don't remember reading anywhere about an LTS for Wagtail but your decision is reasonable.
